---
# tasks file for setup-website-user-access

- name: "Create home directories for user"
  file: 
    path: "{{ setup_website_user_access_web_root }}/{{ item.name }}"
    state: directory 
    owner: root
    group: root
  when: item.create_user
  with_items: '{{ nginx_site_setup_sites_to_set_up }}'

- name: "Add users for each site"
  user:
    name: "{{ item.name }}" 
    home: "{{ setup_website_user_access_web_root }}/{{ item.name }}"
    groups: "www-data"
    shell: /usr/sbin/nologin
    update_password: "always" 
    password: "{{ item.user_password }}"
  with_items: '{{ setup_website_user_access_list }}'
  when: item.create_user

- name: "Add user to sshd_config"
  blockinfile:
    path: /etc/ssh/sshd_config
    block: |
      Match User {{ item.name }}
        ChrootDirectory {{ setup_website_user_access_web_root }}/{{ item.name }}
        X11Forwarding no
        AllowTcpForwarding no
        ForceCommand internal-sftp
    marker: "# {mark} ANSIBLE MANAGED BLOCK {{ item.name }}"
  with_items: '{{ setup_website_user_access_list }}'
  when: item.create_user
  notify: restart sshd
